language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2"  # py.test has no support for Python 3.2
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
  - "pypy"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install virtualenv==15.2.0; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install tox-travis==0.10; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install coveralls==1.3.0; fi
  - pip install tox-travis
  - pip install coveralls
script:
  tox
after_success:
  coveralls
